2 css grimdvl
MastersAcademy/fe-course-basic-2023 pull request #113
Opened 2023-10-20 11:56 UTC by Grimdvl

Навігацію зробив не через гріди а через флекс, тому що некоректно відображалась би анімація хаверу, але я оставив коментарі з грідами сподіваюсь * заслужив)

2023-10-22 15:51 UTC, MZabolotnev requested changes
Do either flex or grid, choose one. And please remove comments.

2023-10-23 06:13 UTC, Grimdvl commented
done

2023-10-23 13:46 UTC, Grimdvl commented
1 more bug fixed

2023-10-25 05:32 UTC, vadym-zinchenko-moc requested changes
<img width="1439" alt="Screenshot 2023-10-25 at 08 31 22" src="https://github.com/MastersAcademy/fe-course-basic-2023/assets/115080771/5a2990f5-c7be-420c-830e-e341eae41c6f">

Hi, you has trouble with footer? is this fixed? need to fix it.

2023-10-25 18:41 UTC, closed without merging