fixed homework2
MastersAcademy/fe-course-basic-2023 pull request #114
Opened 2023-10-20 12:05 UTC by MarkoAndrew93

2023-10-20 17:45 UTC, MZabolotnev requested changes

2023-10-20 17:45 UTC, MZabolotnev commented on homeworks/andrew.markovskiy_MarkoAndrew93/Games/styles.css
> +  color: var(--color-2, #221F1F);
Why do you need a variable here?

2023-10-20 17:45 UTC, MZabolotnev commented on homeworks/andrew.markovskiy_MarkoAndrew93/Games/styles.css
> +  color: var(--color-1, #EF4934);
Why do you need a variable here?

2023-10-21 10:27 UTC, MarkoAndrew93 commented on homeworks/andrew.markovskiy_MarkoAndrew93/Games/styles.css
> +  color: var(--color-2, #221F1F);
the variable is taken from the layout

2023-10-21 10:28 UTC, MarkoAndrew93 commented on homeworks/andrew.markovskiy_MarkoAndrew93/Games/styles.css
> +  color: var(--color-1, #EF4934);
the variable is taken from the layout

2023-10-21 11:34 UTC, closed without merging