feat: create web pages with "About us" and "Cards"
MastersAcademy/fe-course-basic-2023 pull request #118
Opened 2023-10-20 20:25 UTC by vBrusentsov

2023-10-21 07:31 UTC, anna-vrana-moc commented
Hey @vBrusentsov please improve your code and remove fixed width and height in css. You can use only max-width for the parent block to limit the width of content.

2023-10-21 10:49 UTC, vBrusentsov commented
Thank you. I ended refactored code according to your advice

2023-10-21 23:21 UTC, anna-vrana-moc commented
@vBrusentsov You have several unresolved issues. You can find them by scrolling to the top of this conversation or by clicking on the 'Files' tab. Look for the comment right under the line that needs fixing

2023-10-21 23:25 UTC, anna-vrana-moc requested changes

2023-10-22 10:22 UTC, vBrusentsov commented on homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/index.html
> +                <h1>About me</h1>
What are you mean margins?

2023-10-22 18:26 UTC, anna-vrana-moc commented on homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/index.html
> +                <h1>About me</h1>
https://developer.mozilla.org/en-US/docs/Web/CSS/margin

2023-10-22 18:53 UTC, anna-vrana-moc commented
@vBrusentsov please check unresolved conversations (comments) and update your homework

2023-10-22 18:53 UTC, anna-vrana-moc commented on homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/index.html
> +                <div class="main__paragraph">
You don't need any div here, all styles you can apply to the p

2023-10-22 18:53 UTC, anna-vrana-moc commented on homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/index.html
> +                        <br>
This old practice of using tags like 'br', 'i', 'b' should be avoided. Please remove all 'br' tags and split the content by the <p> tag to create paragraphs in the layout

2023-10-22 18:53 UTC, anna-vrana-moc commented on homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/games.html
> +                    <div class="main-card-header">
If you have several simular elements - it's a list. So, it is a list of cards. Please update the structure

2023-10-22 18:53 UTC, anna-vrana-moc commented on homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/games.html
> +                        <div class="card-actor-genre">
card-actor-genre, card-actor-platform, card-actor-publisher, card-actor-developer, card-actor-release_date - don't have any specific styles, so remove them all

2023-10-23 08:46 UTC, anna-vrana-moc approved these changes

2023-10-23 08:46 UTC, merged