task 1 html with img
MastersAcademy/fe-course-basic-2023 pull request #130
Opened 2023-10-21 15:42 UTC by bodiiiick

2023-10-21 18:54 UTC, anna-vrana-moc commented
@bodiiiick hey-hey) please check my comments and specify the font properties of the text

2023-10-21 23:27 UTC, anna-vrana-moc requested changes

2023-10-23 19:29 UTC, bodiiiick reviewed
add max-width line-height font-family

2023-10-24 05:52 UTC, anna-vrana-moc approved these changes

2023-10-24 05:52 UTC, merged