2-css_IgorFromUA - used grid
MastersAcademy/fe-course-basic-2023 pull request #131
Opened 2023-10-21 16:15 UTC by IgorFromUA

added a picture to about , a header with a logo. added a page with cards and a header. used grid.

2023-10-21 19:12 UTC, anna-vrana-moc commented
hi @IgorFromUA I suggested several small improvements to your code. You have done a good job!

2023-10-21 20:51 UTC, IgorFromUA commented
rolled back the commit and created new commits

2023-10-21 23:26 UTC, anna-vrana-moc requested changes

2023-10-22 06:14 UTC, IgorFromUA commented on homeworks/ihor.zapisochniy_IgorFromUA/GamesProject/index.html
> +                        This page was developed during the course <a class="about__link"
this br tag is for decoration, if removed the "about" text will "stick".

2023-10-22 12:21 UTC, anna-vrana-moc approved these changes

2023-10-22 12:21 UTC, merged