added header in index.html, created pokemons page
MastersAcademy/fe-course-basic-2023 pull request #162
Opened 2023-10-23 21:12 UTC by NosatskyiK

Added header in index.html, created pokemons page. 
Fixed bugs in past task (fixed serif on sans-serif).

2023-10-25 06:41 UTC, oleg-nikulin-moc reviewed
Передивись код і виправ водібні речі що я писав

2023-10-26 18:57 UTC, oleg-nikulin-moc commented on homeworks/kostiantyn.nosatskyi_NosatskyiK/PokemonProject/index.html
>          <article>
тут краще б використати <main>

2023-10-26 18:57 UTC, oleg-nikulin-moc commented on homeworks/kostiantyn.nosatskyi_NosatskyiK/PokemonProject/index.html
> +                <img class="section__img-image" src="img/pokemon.png" alt="pokemon">
дуже дивна назва для класу по преше image. дублюєтья по друге в назві класу назва секції

2023-10-26 18:57 UTC, oleg-nikulin-moc commented on homeworks/kostiantyn.nosatskyi_NosatskyiK/PokemonProject/index.html
> +                <p class="main_text">
теж дивна назва ддя класу і використовуй подвійне __

2023-10-26 18:57 UTC, oleg-nikulin-moc commented on homeworks/kostiantyn.nosatskyi_NosatskyiK/PokemonProject/pokemons.css
> +  font-family: "Roboto", sans-serif;
задавай основні стилі для body і тоді вони будуть наслідуватися в інших місйцях тексту і тобі не прийдеться писати скрізь одне і теж

2023-10-26 19:41 UTC, NosatskyiK commented on homeworks/kostiantyn.nosatskyi_NosatskyiK/PokemonProject/index.html
>          <article>
Трішки не зрозумів що краще тут використати

2023-10-27 19:01 UTC, oleg-nikulin-moc commented on homeworks/kostiantyn.nosatskyi_NosatskyiK/PokemonProject/pokemons.css
> +header {
створю клас і задавй стилі йому не тегам

2023-10-27 19:04 UTC, oleg-nikulin-moc requested changes
Зробиш завтра до обіду посталю 1+, не забудь порезолвить коменти

2023-10-27 19:43 UTC, NosatskyiK commented
added class for header, rename article to main, added coment and translate in to english

2023-10-30 07:30 UTC, oleg-nikulin-moc approved these changes

2023-10-30 07:35 UTC, merged