added homework #3
MastersAcademy/fe-course-basic-2023 pull request #163
Opened 2023-10-24 10:59 UTC by Mariya-Artemenko

ready for review

2023-10-24 11:30 UTC, Mariya-Artemenko commented
HW #3 ready for review

2023-10-27 19:05 UTC, oleg-nikulin-moc requested changes

2023-10-28 08:35 UTC, Mariya-Artemenko commented on homeworks/mariya.artemenko_Mariya-Artemenko/PokemonProject/index.html
> +                <ul class="nav_links_list">
додала зміни

2023-10-30 19:02 UTC, vadym-zinchenko-moc approved these changes

2023-10-30 19:03 UTC, merged