3-th task, css
MastersAcademy/fe-course-basic-2023 pull request #164
Opened 2023-10-24 12:26 UTC by NataMimoza

2023-10-25 07:04 UTC, oleg-nikulin-moc reviewed
в тебе багато дрібних помилок, виправ і передивись схожі проблеми по всьому проекту що я відписав

2023-10-25 07:04 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject2/About.html
> +                            <div class="Article">
є тег article передивись в документації теги та як їх використовувати https://w3schoolsua.github.io/html/html5_new_elements.html

2023-10-25 07:04 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject2/Cards.html
> +                                <b>Publisher:</b> Activision Blizzard King
цей тег краще не використовй краще оберни в span і додай клас, до якого додаси жирність, бо різні брацзерни по різному розцміють жирність цього тегу і відмалюють текст по різному

2023-10-25 07:04 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject2/Cards.html
> +                        <div class="image_header">
тут треба використовати або image-header або image__header

2023-10-25 07:04 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject2/Games.css
> +h1 {
стилі задавай тільки через класи

2023-10-25 07:04 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject2/style.css
> +  font-family: Roboto, serif;
стиілі повністю однакові, дублювати їх не треба, просто перевикористай клас

2023-10-27 19:10 UTC, oleg-nikulin-moc requested changes
Перечитай документацію по тегам і спробуй більше семантичних тегів використовувати замість тег div

2023-10-27 19:38 UTC, NataMimoza commented
> Перечитайте документацию по тегам и попробуйте больше семантических тегов, чтобы выбрать заполнение тега div.

Олег, посмотрите пожалуйста, в https://github.com/MastersAcademy/fe-course-basic-2023/pull/197. Я совершенно запуталась, в коммитах во гитхабе, во всем. В 197 пуле есть папка GamesProgect3. Там все задания: переделанное по css и новое по forms. Проверьте пожалуйста там все

2023-10-28 10:06 UTC, NataMimoza commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject2/About.html
> +            <div class="About">
Добрий день. Перегляньте, будь ласка, я наче все остаточно виправила

2023-10-30 20:16 UTC, oleg-nikulin-moc requested changes

2023-10-30 20:16 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/About.html
> +                    <section class="logo-box">
тег section краще використовувати тоді коли тобі якийсь блок треба розділити на частини, тобто на секції ,і по логіці їх має бути мінімум 2, в даному випадку булоб краще виоритати тег div або picture

2023-10-30 20:16 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/About.html
> +                    <div class="section">
не логічно що в тебе врапер з класом section і далі чайлд тег section. як на мене дів взагалі тут зайвий

2023-10-30 20:16 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/About.html
> +                        <section class="image-box">
про врапер для іміджа я вже писав

2023-10-30 20:16 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/Cards.html
> +                            <span class="font">Gende:</span>
тут краще б параграф використовувати а може і хедінги нижчого порядку, span використовуєтсья більше в середині тегів для оформлення тексту

2023-11-01 11:47 UTC, oleg-nikulin-moc approved these changes

2023-11-01 11:48 UTC, merged