3-forms_snischuk
MastersAcademy/fe-course-basic-2023 pull request #176
Opened 2023-10-25 14:40 UTC by snischuk

2023-10-25 15:25 UTC, snischuk commented
![Снимок экрана 2023-10-25 в 18 24 25](https://github.com/MastersAcademy/fe-course-basic-2023/assets/52202397/6f15d535-a2a4-4853-98e7-4ec2280ce417)

чому не пройшов лінтер?

2023-10-26 19:20 UTC, oleg-nikulin-moc commented on homeworks/max.snischuk_snischuk/PokemonProject/index.html
>              <div class="header__container">
як на мене це зайвий врапер і без нього можна обійтися

2023-10-26 20:25 UTC, snischuk commented on homeworks/max.snischuk_snischuk/PokemonProject/index.html
>              <div class="header__container">
видалив

2023-10-26 20:28 UTC, snischuk commented on homeworks/max.snischuk_snischuk/PokemonProject/index.html
>              <div class="header__container">
> як на мене це зайвий врапер і без нього можна обійтися

але як тоді фон виправити?..

2023-10-27 13:09 UTC, oleg-nikulin-moc commented
не забудь повидаляти закоменчений код

2023-10-27 13:28 UTC, snischuk commented
> не забудь повидаляти закоменчений код

вибачаюсь, не помітив їх) дякую)

2023-10-27 13:38 UTC, oleg-nikulin-moc requested changes

2023-10-27 13:38 UTC, oleg-nikulin-moc commented on homeworks/max.snischuk_snischuk/PokemonProject/index.html
>              <div class="header__container">
так ти можеш перенести в nav та зробити space-between, або просто для лого зробити margin-right:auto і в тебе має все стати на свої місця

2023-10-27 14:23 UTC, snischuk commented on homeworks/max.snischuk_snischuk/PokemonProject/pokemons.html
> +                <div class="filters__group">
філдсет обгортає лише однотипні? типу лише радіобаттони чи чекбокси?
чи також можна обертати ним, якщо всередині і type="search" разом з button "submit"?
чи підійде він також для .filters__container?

2023-10-27 14:27 UTC, snischuk commented on homeworks/max.snischuk_snischuk/PokemonProject/pokemons.html
>                      <li class="pokemons__card card-pokemon">
pokemons__card - карточка як елемент блоку покемонс (для позиціюнування)
card-pokemon - незалежний блок без строгого позиціюнування (щоб можна було переміщати в будь-яке місце)

чи я не правильно зрозумів БЕМ?(

2023-10-27 19:15 UTC, oleg-nikulin-moc commented on homeworks/max.snischuk_snischuk/PokemonProject/pokemons.html
> +                <div class="filters__group">
він ідеально підходить для .filters__container

2023-10-27 19:18 UTC, oleg-nikulin-moc commented on homeworks/max.snischuk_snischuk/PokemonProject/pokemons.html
>                      <li class="pokemons__card card-pokemon">
просто нави мені не подобаються, мені здається що краще булоб щось типу pokemons__card-item card-pokemon так трохи краще. Але дивись як хочеш, це не особо впливає, просто моя субєктивна думка.

2023-10-27 19:19 UTC, oleg-nikulin-moc requested changes
Виправ все до завтрішнього обіду, атм трохи, і буде 1+*

2023-10-27 22:50 UTC, snischuk commented
> Виправ все до завтрішнього обіду, атм трохи, і буде 1+*

дізнався багато нюансів!) дуже дякую за код-ревью)

2023-10-30 07:38 UTC, oleg-nikulin-moc approved these changes

2023-10-30 07:38 UTC, merged