3 forms lesiaturuta
MastersAcademy/fe-course-basic-2023 pull request #181
Opened 2023-10-25 20:42 UTC by lesiaturuta

2023-10-26 19:42 UTC, oleg-nikulin-moc requested changes

2023-10-26 19:42 UTC, oleg-nikulin-moc commented on homeworks/lesia.turua_lesiaturuta/PokemonProject/cards.html
> +                    <div class="form__search-radio">
для враперів використовуй fieldset

2023-10-26 19:42 UTC, oleg-nikulin-moc commented on homeworks/lesia.turua_lesiaturuta/PokemonProject/get-result.html
> +            <a class="result__link" href="./cards.html">
не обертай ніколи так, ти використовуєш або лінку або button якщо тобі треба в середині лінки блок, то додаєш span

2023-10-26 19:42 UTC, oleg-nikulin-moc commented on homeworks/lesia.turua_lesiaturuta/PokemonProject/style.css
> +.login__form-checkbox-input + label,
не викорисовуй теги в стилях додавай класи

2023-10-27 18:54 UTC, lesiaturuta commented on homeworks/lesia.turua_lesiaturuta/PokemonProject/cards.html
> +                    <div class="form__search-radio">
used fieldset

2023-10-27 18:55 UTC, lesiaturuta commented on homeworks/lesia.turua_lesiaturuta/PokemonProject/get-result.html
> +            <a class="result__link" href="./cards.html">
removed button and added span

2023-10-27 18:55 UTC, lesiaturuta commented on homeworks/lesia.turua_lesiaturuta/PokemonProject/style.css
> +.login__form-checkbox-input + label,
added class name

2023-10-27 19:20 UTC, oleg-nikulin-moc commented on homeworks/lesia.turua_lesiaturuta/PokemonProject/cards.html
> +                            <br>
br тут зайвий, треба відступ використовуй margin

2023-10-27 19:35 UTC, oleg-nikulin-moc reviewed
пофікси завтра до обіду і буде 1+*

2023-10-27 19:35 UTC, oleg-nikulin-moc commented on homeworks/lesia.turua_lesiaturuta/PokemonProject/cards.html
> +                            <input class="form__search-radio-radio gap-right6" type="radio" id="Only_new" name="sel" checked
id має бути only-new або onlyNew

2023-10-27 19:53 UTC, lesiaturuta commented on homeworks/lesia.turua_lesiaturuta/PokemonProject/cards.html
> +                            <br>
deleted br, there were simply extra

2023-10-27 19:53 UTC, lesiaturuta commented on homeworks/lesia.turua_lesiaturuta/PokemonProject/cards.html
> +                            <input class="form__search-radio-radio gap-right6" type="radio" id="Only_new" name="sel" checked
fixed name id

2023-10-30 19:33 UTC, vadym-zinchenko-moc requested changes
Пропущений поінт із завдання:
- Якщо чекбокс не відмічeнbq, або незаповнені поля для пошти чи пароля, форма відправлятися не повинна.

2023-10-31 07:06 UTC, vadym-zinchenko-moc approved these changes

2023-10-31 07:06 UTC, merged