4 js basics demasha0908
MastersAcademy/fe-course-basic-2023 pull request #191
Opened 2023-10-26 17:31 UTC by demasha0908

2023-10-26 19:49 UTC, oleg-nikulin-moc requested changes

2023-10-26 19:49 UTC, oleg-nikulin-moc commented on homeworks/mariia.demchenko_demasha0908/4-basics/basics.css
> +.basics__operations {
навіщо тобі дублювати ці стилі, створи краще окремий клас і назови щоб можна було використовувати в різнтих місцях .або навіть додай font-size до body, і тоді в тіоєму випадку не потрібно буде і класи додавати

2023-10-27 04:37 UTC, demasha0908 commented on homeworks/mariia.demchenko_demasha0908/4-basics/basics.css
> +.basics__operations {
виправила, зрозуміла, що треба максимально уникати дубляжу, тоді і код менше писати треба буде)

2023-10-27 19:37 UTC, oleg-nikulin-moc approved these changes
Молодець, гарна робота

2023-10-27 19:37 UTC, merged