4-js_basics_snischuk
MastersAcademy/fe-course-basic-2023 pull request #195
Opened 2023-10-26 20:09 UTC by snischuk

2023-10-27 19:43 UTC, oleg-nikulin-moc requested changes

2023-10-27 19:43 UTC, oleg-nikulin-moc commented on homeworks/max.snischuk_snischuk/4-basics/basics.js
> +const mathResultsNode = document.querySelector('.math-results');
краще додай до блоку .math-results дата атрибут і звертайся до нього типу data-result document.querySelector('[data-result]'); якщо в тебе немає виходу і треба додавати до класу то додавай префікс js. Має бути js-math-results щоб коли будеш в команді працювати ніхто не видалив цей клас, а таке може бути і логіка не зламалася.

2023-10-27 23:33 UTC, snischuk commented on homeworks/max.snischuk_snischuk/4-basics/basics.js
> +const mathResultsNode = document.querySelector('.math-results');
як зрозуміти коли потрібні дата-атрибути?

2023-10-30 20:19 UTC, oleg-nikulin-moc commented on homeworks/max.snischuk_snischuk/4-basics/basics.js
> +const mathResultsNode = document.querySelector('.math-results');
в загалі гарним тоном вважаєтсья звертатися до дому через дата атрибути тому звертайся завжди, використання id і класів не бажано і тільки в окремих випадках

2023-10-30 20:20 UTC, oleg-nikulin-moc approved these changes

2023-10-30 20:20 UTC, merged