added homework 4-basic
MastersAcademy/fe-course-basic-2023 pull request #204
Opened 2023-10-27 18:01 UTC by lesiaturuta

2023-10-27 20:30 UTC, oleg-nikulin-moc commented on homeworks/lesia.turua_lesiaturuta/4-basics/basics.js
> +const X = 2;
змінні та константи  пишуться камелкейсом, але якщо одна літера то з маленької

2023-10-27 20:36 UTC, oleg-nikulin-moc requested changes

2023-10-27 20:36 UTC, oleg-nikulin-moc commented on homeworks/lesia.turua_lesiaturuta/4-basics/basics.js
> +const additionEl = document.querySelector('.addition');
звертайся не до класу а до дата атрибуту, для цього тобі треба додати в html lj ghbrkfle data-additional  і звернутися до нього document.querySelector('[data-addition]'); класи залиш для стилів

2023-10-27 20:36 UTC, oleg-nikulin-moc commented on homeworks/lesia.turua_lesiaturuta/4-basics/basics.js
> +const stringAddition = `Додавання: ${X} + ${Y} = ${addition}`;
так теж можна робити але текст я б виніс в html так як він не динамічний і додавби туди якийсь span в який і додава би значенняю

2023-10-27 20:36 UTC, oleg-nikulin-moc commented on homeworks/lesia.turua_lesiaturuta/4-basics/index.html
> +        <h1 class="text">Basic math operation</h1>
для тайтла в тебе клас text а для текста card__header-title, щось не логічно, також намагайся тримати стиль, частина стилів по БЕМу, частина звичайн назви.

2023-10-28 18:53 UTC, lesiaturuta commented on homeworks/lesia.turua_lesiaturuta/4-basics/basics.js
> +const X = 2;
fixed

2023-10-28 18:54 UTC, lesiaturuta commented on homeworks/lesia.turua_lesiaturuta/4-basics/basics.js
> +const additionEl = document.querySelector('.addition');
fixed

2023-10-28 18:55 UTC, lesiaturuta commented on homeworks/lesia.turua_lesiaturuta/4-basics/basics.js
> +const stringAddition = `Додавання: ${X} + ${Y} = ${addition}`;
fixed and added name for alert and console log

2023-10-28 18:55 UTC, lesiaturuta commented on homeworks/lesia.turua_lesiaturuta/4-basics/index.html
> +        <h1 class="text">Basic math operation</h1>
added new name

2023-10-30 19:32 UTC, vadym-zinchenko-moc approved these changes

2023-10-30 19:32 UTC, merged