3 forms yana dankova
MastersAcademy/fe-course-basic-2023 pull request #212
Opened 2023-10-28 09:51 UTC by YanaDankova

2023-10-28 18:25 UTC, MZabolotnev commented
Також відступи між полями і розмір кнопки не відповідають дизайну. Зрівняй будь ласка з макетом і додай відступів.

2023-10-28 18:27 UTC, MZabolotnev commented
На сторінці з результатом має бути кнопка що веде на домашню сторінку.

2023-10-29 05:44 UTC, YanaDankova commented
Додала кнопку і відступи. Дякую за ваші зауваження.

2023-10-29 17:52 UTC, MZabolotnev commented
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/25617217/a273448d-3cd5-44cb-add9-69b30c5d0680)
Текст має бути жирнішим. 
Кнопка має бути такої ж довжини як і текстові поля. 
Кнопка має мати радіус бордера, а не прямі кути. 
Result page зроби в тому самому стилі як і форму. Відцентруй і тд.

2023-10-29 17:53 UTC, MZabolotnev requested changes

2023-10-29 17:53 UTC, MZabolotnev commented on homeworks/yana.dankova_YanaDankova/GamesProject/login.html
> +                    </div>
@YanaDankova що з приводу цього фіксу?

2023-10-30 12:32 UTC, YanaDankova commented
Добрий день) виправила наче

2023-10-30 19:10 UTC, MZabolotnev approved these changes

2023-10-30 19:26 UTC, merged