add login page
MastersAcademy/fe-course-basic-2023 pull request #214
Opened 2023-10-28 13:10 UTC by YanaHaivoronska

add result page
add some styles

2023-10-30 19:43 UTC, MZabolotnev commented
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/25617217/7328050c-eed1-47c0-98b3-63020c1fac3b)
Звір дизайн і свою форму, є невідповідності. Текст кнопки має бути по центру вертикально ( перевір відступи ). Чекбокс і його лейбл мають бути на одній лінії. 
Між інпутом паролю і чекбоксом теж має бути відступ, в тебе його не має.

2023-10-30 19:43 UTC, MZabolotnev requested changes

2023-10-30 19:43 UTC, MZabolotnev commented on homeworks/yana.haivoronska_Yana_Haivoronska/Game Project/login.html
> +                <label for="email">
Має бути одна форма, і всі інпути всередині неї. В тебе зараз кожен інпут всередині своєі форми, це невірно. Як наслідок, тепер в тебе не працює валідація, і я можу відправити незаповнену форму

2023-10-30 19:43 UTC, MZabolotnev commented on homeworks/yana.haivoronska_Yana_Haivoronska/Game Project/Result.html
> +        <h1>Access is allowed</h1>
Тут має також бути кнопка повернення на домашню сторінку

2023-10-30 21:26 UTC, YanaHaivoronska commented on homeworks/yana.haivoronska_Yana_Haivoronska/Game Project/login.html
> +                <label for="email">
Ok , thank you for  comments and indications . On my way tô pc and looking for solutions .

2023-11-04 15:03 UTC, MZabolotnev approved these changes

2023-11-04 15:03 UTC, merged