3-rd task, forms
MastersAcademy/fe-course-basic-2023 pull request #216
Opened 2023-10-28 14:40 UTC by NataMimoza

2023-10-28 14:48 UTC, NataMimoza commented
Відправляла файли тільки по формам, але чомусь залетіло все(

2023-10-30 20:32 UTC, oleg-nikulin-moc requested changes
ТАкож тут є помилки з попереднього ПР, треба або щоб ти потім померджила або пофіксила

2023-10-30 20:32 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/Login.css
> +input[type="email"]:invalid + .invalid-feedback::after {
використоуй класи, не додавай спецефічності,

2023-10-30 20:32 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/Login.css
> +  width: 575px;
на майбутне намагайся менше викорисовувати фіксовані висоту і ширину, використову більше min-width, max-width, min-height, max-height

2023-11-01 20:15 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/Login.html
> +                            <input type="email" id="email" name="email" class="input-box" placeholder="Enter your email address" required>
для поля email в тебе має бути перевірка, має бути доданий атрибут pattern з regeX

2023-11-01 20:16 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/Login.css
> +  padding: 0 52px 0 53px;
це не помилка, але різниця в 1px не значна, але якщо ти зробиш сторони однаковими, то можна зробити коротший запис padding: 0 52px;

2023-11-01 20:18 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/Login.html
> +                    <section class="logo-box">
в минулій роботі ти заміняла тут section -> div

2023-11-01 20:19 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/Login.html
> +                            <input type="submit" class="button-login" value="Login">
input  type submit зараз не використовуєтья, його замінюють на тег button type="submit"

2023-11-01 20:20 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/style.css
> +.text3 {
погана назва для класу

2023-11-01 20:21 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/style.css
> +.text3 {
також в тебе значення однакові в цих классах, зроби нормальний клас і додай його до цих блоків. тобто один клас заюзай в цих блоках.

2023-11-01 20:22 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/style.css
> +  font-family: Roboto, serif;
Взагалі font-family винеси в тег body і тобі не треба буде його скрізь прописувати, він буде наслідуватися, туди ж ти можеш винести  font-size і інші стилі для тексту що найбільше повторюються.

2023-11-01 20:24 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/style.css
> +.main-title {
цей клас наче ніде не використовується, якщо так то прибери його і передивися стилі, щоб не було класів, які не використовуються.

2023-11-02 11:05 UTC, NataMimoza commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/Login.html
> +                            <input type="email" id="email" name="email" class="input-box" placeholder="Enter your email address" required>
додала

2023-11-02 11:05 UTC, NataMimoza commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/style.css
> +.main-title {
використовується для головного заголовку

2023-11-02 11:05 UTC, NataMimoza commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/style.css
> +.text3 {
Я їх прибрала ще в перший раз, напевно, при злитті гілок залетіли

2023-11-02 11:06 UTC, NataMimoza commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/Login.html
> +                            <input type="submit" class="button-login" value="Login">
виправила

2023-11-02 11:06 UTC, NataMimoza commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/Login.html
> +                    <section class="logo-box">
виправила

2023-11-02 21:45 UTC, oleg-nikulin-moc approved these changes

2023-11-02 21:46 UTC, oleg-nikulin-moc commented
Молодець, ти справилася!

2023-11-02 21:46 UTC, merged