4 js basics mariya artemenko
MastersAcademy/fe-course-basic-2023 pull request #221
Opened 2023-10-28 17:37 UTC by Mariya-Artemenko

2023-10-28 17:44 UTC, Mariya-Artemenko commented
ready for review @oleg-nikulin-moc

2023-10-30 19:14 UTC, vadym-zinchenko-moc requested changes
Please remove the alerts() it's a long time to click OK after each result. =)
Enough that we see everything in html!.
Also, please add classes to styled elements.
And I can approve request

2023-10-30 20:25 UTC, Mariya-Artemenko commented
@vadym-zinchenko-moc added changes according to your comments. Please check =)

2023-10-31 07:04 UTC, vadym-zinchenko-moc approved these changes

2023-10-31 07:05 UTC, merged