add 4-basics
MastersAcademy/fe-course-basic-2023 pull request #226
Opened 2023-10-29 13:58 UTC by DavidTereshchenko

I did it this way because I didn't have time
tomorrow I will try to do it from DOM

2023-10-30 05:21 UTC, anna-vrana-moc requested changes

2023-10-30 05:21 UTC, anna-vrana-moc commented on homeworks/david.tereshchenko_DavidTereshchenko/4-basics/index.html
> +    <body>
Use HTML for rendering the results. HTML loads faster, allowing users to see some content while the page is loading. Please create the HTML content in the index.html file

2023-10-30 05:21 UTC, anna-vrana-moc commented on homeworks/david.tereshchenko_DavidTereshchenko/4-basics/index.html
> +    <body>
Get HTML element by data-attributes

2023-10-30 05:21 UTC, anna-vrana-moc commented on homeworks/david.tereshchenko_DavidTereshchenko/4-basics/basics.js
> +const secondNumber = +prompt('Enter the second number', '').trim();
It is so many prompts. Use it to get the numbers and render all results on the page

2023-10-31 08:02 UTC, anna-vrana-moc commented
Please fix linter errors

2023-10-31 11:01 UTC, anna-vrana-moc approved these changes

2023-10-31 11:04 UTC, anna-vrana-moc commented
Hey @DavidTereshchenko great job! I like it) For the future get HTML elements by data-attributes, like data-result, because somebody can remove your class to fix css and broke the logic

2023-10-31 11:04 UTC, merged

2023-10-31 11:07 UTC, DavidTereshchenko commented
ok, I'll pay attention to that, thanks