4-th task, JS
MastersAcademy/fe-course-basic-2023 pull request #228
Opened 2023-10-29 17:20 UTC by NataMimoza

2023-10-30 20:29 UTC, MZabolotnev requested changes

2023-10-30 20:29 UTC, MZabolotnev commented on homeworks/Natalia.Alifirovets_NataMimoza/4-basics/basics.html
> +                </li>
Привіт! А як це власне має працювати?) Це статичний текст, а має бути динамічний вивід результатів операцій.

2023-10-31 19:45 UTC, NataMimoza commented on homeworks/Natalia.Alifirovets_NataMimoza/4-basics/basics.html
> +                </li>
Miron, I've fixed basic.html

2023-11-04 15:03 UTC, MZabolotnev approved these changes

2023-11-04 15:03 UTC, merged