creation of a new branch and a new PR
MastersAcademy/fe-course-basic-2023 pull request #262
Opened 2023-11-02 21:41 UTC by NosatskyiK

created a new pr because the old one that was created on Sunday had conflicts that he could not fix, and created a new branch

2023-11-02 21:55 UTC, oleg-nikulin-moc commented on homeworks/kostiantyn.nosatskyi_NosatskyiK/4-js_basics/basics.js
> +document.getElementById('addition').textContent = sum;
це не помилка, але намагайся використовувати дата атрибути для роботи з html, звертатися можна document.querySelector('[data-substraction]')

2023-11-02 21:57 UTC, oleg-nikulin-moc commented on homeworks/kostiantyn.nosatskyi_NosatskyiK/4-js_basics/index.html
> +                    Operation subtraction = <span id="subtraction"></span>
тут просто додаєш атрибут data-substraction і звертаєшся до нього Дата атрибу краще тим що можна додавати його до кількох елементів і тоді ти отримуєш масив елементів ,id не можна. і ще куча плюшок

2023-11-02 21:57 UTC, oleg-nikulin-moc requested changes
Спробуй зробити через дата атрибути

2023-11-03 17:06 UTC, NosatskyiK commented
Замінив всі id на data атрибути. Робив це перший раз, тому буду вдячний якщо вкажиш на недоліки

2023-11-03 21:32 UTC, oleg-nikulin-moc approved these changes
Все гарно, молодець!

2023-11-03 21:33 UTC, merged