5-js_logic_snischuk
MastersAcademy/fe-course-basic-2023 pull request #266
Opened 2023-11-03 18:33 UTC by snischuk

2023-11-03 21:44 UTC, oleg-nikulin-moc commented on homeworks/max.snischuk_snischuk/5-logic/style.css
> +h1 {
не лінуйся створювати класи для елементів, тк їх тут мало, але щоб не перейшло тобі в звичку, бо в великих проектах буде купа проблем з цим. особливо при масштабувані коду

2023-11-03 22:06 UTC, oleg-nikulin-moc commented
Передивись чому в тебе заміни не тільки по цьому завданю але і по старому

2023-11-03 22:08 UTC, oleg-nikulin-moc requested changes

2023-11-03 22:08 UTC, oleg-nikulin-moc commented on homeworks/max.snischuk_snischuk/5-logic/script.js
> +const FIRST_VALUE_ELEMENT = document.getElementById('firstValue');
спробуй звертатися до data атрибутів, звернення до id не є помилкою але гарним тоном є звернення до дата атрибутів до прикладу data-first-value, звернення document.querySelector('[data-first-value]') Плюси ти можеш прописувати однакові дата атрибути і querySelectorAll поверне тобі масив елементів, і ти можеш зберігати в них якісь дані до прикладу data-value="first"

2023-11-04 00:23 UTC, snischuk commented on homeworks/max.snischuk_snischuk/5-logic/style.css
> +h1 {
я просто думав, що код який надав ментор не можна чіпати)
виправив)

2023-11-04 00:24 UTC, snischuk commented on homeworks/max.snischuk_snischuk/5-logic/script.js
> +const FIRST_VALUE_ELEMENT = document.getElementById('firstValue');
тут також думав, що код який надав ментор не можна чіпати)
виправив)

2023-11-04 00:28 UTC, snischuk commented on homeworks/max.snischuk_snischuk/5-logic/script.js
> +const FIRST_VALUE_ELEMENT = document.getElementById('firstValue');
дякую, за додаткове пояснення про дата-атрибути) мб цей мій тягар надовго)

2023-11-04 00:30 UTC, snischuk commented
> Передивись чому в тебе заміни не тільки по цьому завданю але і по старому

вроді й поняв) але вроді й не поняв) передивитись чому в мене що?)

2023-11-04 00:32 UTC, snischuk commented
task for 1+* is ready to review

2023-11-05 21:19 UTC, oleg-nikulin-moc approved these changes

2023-11-05 21:19 UTC, merged