5-th task, js logic
MastersAcademy/fe-course-basic-2023 pull request #267
Opened 2023-11-03 19:39 UTC by NataMimoza

2023-11-03 21:58 UTC, oleg-nikulin-moc requested changes

2023-11-03 21:58 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/5-logic/script.js
> +const FIRST_VALUE_ELEMENT = document.getElementById('firstValue');
спробуй звертатися до дата атрибуту  document.querySelector('[data-value-first]'), по id можна звертатися і це не є помилкою, але гарним тоном є звертатися по дата атрибуту, також ти можеш додавати одні дата атрибути до різних елементів і потім querySelectorAll можеш отримати масив елементів. такого з. id не зробиш і там ще є купа плюшек так робити.

2023-11-03 21:58 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/5-logic/homework.js
> +    if (result > 100) {
в тебе немає перевірки ділення на нуль і на те що одне з поілв може бути пустим https://tppr.me/n0Lln та https://tppr.me/4X4MS

2023-11-04 20:39 UTC, NataMimoza commented on homeworks/Natalia.Alifirovets_NataMimoza/5-logic/homework.js
> +    if (result > 100) {
Додала

2023-11-05 21:27 UTC, oleg-nikulin-moc approved these changes

2023-11-05 21:28 UTC, merged