added homework 5-js_logic
MastersAcademy/fe-course-basic-2023 pull request #268
Opened 2023-11-03 20:18 UTC by Mariya-Artemenko

2023-11-03 20:28 UTC, Mariya-Artemenko commented
ready for review, please check @oleg-nikulin-moc =)

2023-11-03 22:07 UTC, oleg-nikulin-moc requested changes

2023-11-03 22:07 UTC, oleg-nikulin-moc commented on homeworks/mariya.artemenko_Mariya-Artemenko/5-logic/index.html
> +                        <option class="select__option" value="+">+</option>
якась біда зі стилями https://tppr.me/We4JW

2023-11-03 22:07 UTC, oleg-nikulin-moc commented on homeworks/mariya.artemenko_Mariya-Artemenko/5-logic/homework.js
> +        result = 'Result is too big';
немає перевірки ділення на нуль і також перевірки на пусте поле https://tppr.me/hswWc

2023-11-03 22:07 UTC, oleg-nikulin-moc commented on homeworks/mariya.artemenko_Mariya-Artemenko/5-logic/script.js
> +const FIRST_VALUE_ELEMENT = document.getElementById('firstValue');
спробуй звертатися до дата атрибуту document.querySelector('[data-value-first]'), по id можна звертатися і це не є помилкою, але гарним тоном є звертатися по дата атрибуту, також ти можеш додавати одні дата атрибути до різних елементів і потім querySelectorAll можеш отримати масив елементів. такого з. id не зробиш і там ще є купа плюшек так робити.

2023-11-05 15:53 UTC, Mariya-Artemenko commented
@oleg-nikulin-moc додала зміни, згідно коментарів, переглянь будь ласка

2023-11-05 21:37 UTC, oleg-nikulin-moc approved these changes

2023-11-05 21:37 UTC, merged