JS-Logic
MastersAcademy/fe-course-basic-2023 pull request #270
Opened 2023-11-03 20:33 UTC by Bogdandrummer

2023-11-04 10:47 UTC, Bogdandrummer commented
Calculator.html locates in GameProject /html/

2023-11-04 12:55 UTC, vadym-zinchenko-moc requested changes
![Screenshot 2023-11-04 at 14 48 28](https://github.com/MastersAcademy/fe-course-basic-2023/assets/115080771/c4f7dd4d-bca5-4bf3-a064-72dad48079f8)

На всіх сторінках має бути лінка на калькулятор

![Screenshot 2023-11-04 at 14 48 14](https://github.com/MastersAcademy/fe-course-basic-2023/assets/115080771/e7d3432e-332c-46fb-8e5f-701967ec89e1)

пусте поле, а чомусь воводиться нуль! Краще додати валідацію щоб всі поля були заповнені!
![Screenshot 2023-11-04 at 14 46 40](https://github.com/MastersAcademy/fe-course-basic-2023/assets/115080771/870cd21d-e358-4b8c-9e55-3e1cffb3b3d4)

те ж саме!

2023-11-04 12:55 UTC, vadym-zinchenko-moc commented on homeworks/bogdan.yatsentiuk_Bogdandrummer/5-logic/index.html
> +                        <option class="option" value="+">+</option>
class `option` для тегу `option`???

2023-11-04 12:55 UTC, vadym-zinchenko-moc commented on homeworks/bogdan.yatsentiuk_Bogdandrummer/5-logic/index.html
> +        <div class="field">
`field` переводиться як поле а в нас цілий блок

2023-11-04 12:55 UTC, vadym-zinchenko-moc commented on homeworks/bogdan.yatsentiuk_Bogdandrummer/5-logic/style.css
> +.input {
`input` та ж сама ситуація як із `option`! Все переписати по BEM!

2023-11-04 12:57 UTC, vadym-zinchenko-moc commented
![Screenshot 2023-11-04 at 14 56 39](https://github.com/MastersAcademy/fe-course-basic-2023/assets/115080771/8eec3fe7-ae37-4acc-94f6-9ce8ca465025)
чому кратинки розкидані? не краще було б створити папку images і все туди скласти?

2023-11-04 14:02 UTC, Bogdandrummer commented
А куди саме додати посилання на калькулятор?

2023-11-05 20:07 UTC, vadym-zinchenko-moc approved these changes

2023-11-05 20:07 UTC, merged