added hometask 6
MastersAcademy/fe-course-basic-2023 pull request #301
Opened 2023-11-12 08:13 UTC by Mariya-Artemenko

2023-11-12 08:30 UTC, Mariya-Artemenko commented
@oleg-nikulin-moc ready for review

2023-11-14 21:26 UTC, oleg-nikulin-moc requested changes

2023-11-14 21:26 UTC, oleg-nikulin-moc commented on homeworks/mariya.artemenko_Mariya-Artemenko/PokemonProject/css/login.css
> +input[type="text"] {
намагайся звикати використовувати класи а не селектори

2023-11-14 21:26 UTC, oleg-nikulin-moc commented on homeworks/mariya.artemenko_Mariya-Artemenko/PokemonProject/login.html
>                              pattern="[a-z0-9._%+\-]*@[a-z0-9.\-]*\.[a-z]{2,}$"
валідацію з html по завданю треба видалити

2023-11-14 21:26 UTC, oleg-nikulin-moc commented on homeworks/mariya.artemenko_Mariya-Artemenko/PokemonProject/scripts/script.js
> +    return /\S+@\S+\.\S+/.test(email);
цнй регекс не ильно гарний і буде пропускати невалідні емейли до прикладу user@domain: Відсутній символ "." після символу "@". або 
user@domain.: Відсутній конкретний домен верхнього рівня (TLD) після крапки або ж
user@ domain.com: Присутній пробіл після символу "@".

2023-11-14 21:26 UTC, oleg-nikulin-moc commented on homeworks/mariya.artemenko_Mariya-Artemenko/PokemonProject/scripts/script.js
> +submitButton.onclick = validateForm;
краще використовувати так submitButton.addEventListener('click', validateForm);

2023-11-15 17:13 UTC, Mariya-Artemenko commented on homeworks/mariya.artemenko_Mariya-Artemenko/PokemonProject/login.html
>                              pattern="[a-z0-9._%+\-]*@[a-z0-9.\-]*\.[a-z]{2,}$"
@oleg-nikulin-moc внесла зміни

2023-11-15 17:13 UTC, Mariya-Artemenko commented on homeworks/mariya.artemenko_Mariya-Artemenko/PokemonProject/css/login.css
> +input[type="text"] {
@oleg-nikulin-moc внесла зміни

2023-11-15 17:26 UTC, Mariya-Artemenko commented on homeworks/mariya.artemenko_Mariya-Artemenko/PokemonProject/scripts/script.js
> +    return /\S+@\S+\.\S+/.test(email);
@oleg-nikulin-moc цей код вже був у шаблоні, який потрібно було (згідно завдання скопіювати), в завданні немає інф. про те що потрібно правити вже існуючі функції. https://i.imgur.com/XH7y4Ev.png https://i.imgur.com/fiqILnK.png

2023-11-15 17:27 UTC, Mariya-Artemenko commented on homeworks/mariya.artemenko_Mariya-Artemenko/PokemonProject/scripts/script.js
> +submitButton.onclick = validateForm;
@oleg-nikulin-moc аналогічно попередньому комм. в завданні не було інф., що потрібно правити існуючі функції в файлі. Власний код потрібно вставити у функцію function validateForm()  https://i.imgur.com/nFQxyhM.png

2023-11-15 20:39 UTC, oleg-nikulin-moc commented on homeworks/mariya.artemenko_Mariya-Artemenko/PokemonProject/scripts/script.js
> +    return /\S+@\S+\.\S+/.test(email);
я тебе зрозумів, значить якась редиска дала не вірний регекс. ТОді залишай але в інших проектах краще не використовуй

2023-11-15 20:39 UTC, oleg-nikulin-moc commented on homeworks/mariya.artemenko_Mariya-Artemenko/PokemonProject/scripts/script.js
> +submitButton.onclick = validateForm;
зрозумів

2023-11-15 20:40 UTC, oleg-nikulin-moc commented on homeworks/mariya.artemenko_Mariya-Artemenko/PokemonProject/scripts/script.js
> +submitButton.onclick = validateForm;
Мабуть треба теж на лекції ходити)

2023-11-15 20:40 UTC, oleg-nikulin-moc approved these changes

2023-11-15 21:07 UTC, merged