6 functions_NosatskyiK
MastersAcademy/fe-course-basic-2023 pull request #306
Opened 2023-11-12 16:13 UTC by NosatskyiK

Використовував ІД замість дата атрибутів, тому що вони були в ісходніках, але за потреби можу спробувати реалізувати з ними. Також закоментував деякі функції якими не користувався під час виконаня завдання з зірочкою щоб лінтер не сварився.

2023-11-14 21:44 UTC, oleg-nikulin-moc requested changes
Також при кліку на кнопку, в тебе вилазить браузерне вікн, такого не має бути https://tppr.me/LH0FC.

2023-11-14 21:44 UTC, oleg-nikulin-moc commented on homeworks/kostiantyn.nosatskyi_NosatskyiK/6-functions/script/scripts.js
> +    const email = getValueById(EMAIL_INPUT_ID);
це краше let адже значення змінюются

2023-11-14 21:44 UTC, oleg-nikulin-moc commented on homeworks/kostiantyn.nosatskyi_NosatskyiK/6-functions/script/scripts.js
> +    return /\S+@\S+\.\S+/.test(email);
це погана валідація і буде пропускати деякі не валідні емейли

2023-11-16 15:55 UTC, NosatskyiK commented
Видалив поле alert - тепер при помилках видає тільки текст внизу інпута. Замінив регулярний вираз на більш складний. Хотів замінити const на let, але лінтер ругається що ці зміни більше не використовуються тому має бути const
/Users/admin/Documents/MA_FE/fe-course-basic-2023/homeworks/kostiantyn.nosatskyi_NosatskyiK/6-functions/script/scripts.js
   98:9  error  'email' is never reassigned. Use 'const' instead     prefer-const
   99:9  error  'password' is never reassigned. Use 'const' instead  prefer-const
  100:9  error  'checkbox' is never reassigned. Use 'const' instead  prefer-const

✖ 3 problems (3 errors, 0 warnings)
  3 errors and 0 warnings potentially fixable with the --fix option.

2023-11-20 08:03 UTC, oleg-nikulin-moc commented
> Видалив поле alert - тепер при помилках видає тільки текст внизу інпута. Замінив регулярний вираз на більш складний. Хотів замінити const на let, але лінтер ругається що ці змінні більше не використовуються тому має бути const /Users/admin/Documents/MA_FE/fe-course-basic-2023/homeworks/kostiantyn.nosatskyi_NosatskyiK/6-functions/script/scripts.js 98:9 error 'email' is never reassigned. Use 'const' instead prefer-const 99:9 error 'password' is never reassigned. Use 'const' instead prefer-const 100:9 error 'checkbox' is never reassigned. Use 'const' instead prefer-const
> 
> ✖ 3 problems (3 errors, 0 warnings) 3 errors and 0 warnings potentially fixable with the --fix option.
Ввевері загляну

2023-11-20 22:02 UTC, oleg-nikulin-moc requested changes

2023-11-20 22:02 UTC, oleg-nikulin-moc commented on homeworks/kostiantyn.nosatskyi_NosatskyiK/6-functions/login.html
> +                        <input type="text" name="password" id="password" placeholder="Enter your password">
поле з паролем обовязково має бути type="password"

2023-11-20 22:02 UTC, oleg-nikulin-moc commented on homeworks/kostiantyn.nosatskyi_NosatskyiK/6-functions/script/scripts.js
> +        document.getElementById('output-email').textContent = ('Email вийшов чудовий!');
якщо ти додаєш тестовки success то маєш змінювати і колір, до прикладу на зелений, бо вигляжає як помилка

2023-11-22 16:46 UTC, NosatskyiK commented
В CSS файлах замінив input на клас. Додав до поля пароль тип "password". Реалізував зміну кольору виводу тексту у результаті успішної валідації

2023-11-24 20:23 UTC, oleg-nikulin-moc approved these changes

2023-11-24 20:23 UTC, merged