Homework 6 - JS Function & Object
MastersAcademy/fe-course-basic-2023 pull request #312
Opened 2023-11-13 13:13 UTC by LotusElize

2023-11-18 12:57 UTC, MZabolotnev requested changes
Привіт! А чому в домашці є зміни в усьому проекті по всім домашкам?

2023-11-18 20:52 UTC, LotusElize commented
> Привіт! А чому в домашці є зміни в усьому проекті по всім домашкам?

Щось перероблював, структуру трохи переробив, можливо ще вплинуло що я декількка разів видаляв домашку і заносив  в бекапу коли не міг запушити данні, бо не розумів що не так, а так не можна допрацьовувати проєкт по ходу навчання ? Це ускладнить мердж ? Я ж наче тільки свій проєкт змінював і не начий інший це не вплине (якщо я не помиляюсь)

2023-11-23 14:38 UTC, LotusElize commented
Добрий день @MZabolotnev 
Перевірте будь ласка домашні, Homework 6 та Homework 7, вже висять давно, и можу я робити [Optional] Homework 7.5   ?
Вже на черзі Homework 8

Вибачте що турбую.

2023-11-23 14:46 UTC, MZabolotnev commented
Привіт! Допрацьовувати проект можна і треба, але в пулл реквесті домашки мають бути зміни по домашці і більше нічого. Допрацьовувати проект можеш в іншій гілці, і мерджити туди собі останні зміни

2023-11-23 15:58 UTC, LotusElize commented
@MZabolotnev 
Дякую.

Зробив ще комміт з потрібними змінами по домашці 
https://github.com/MastersAcademy/fe-course-basic-2023/pull/312/commits/477c8c65b2ea84e9092a739b911c2f64ad975abd

Там тільки js+html+css стилі помилки.
можна його змержити ? Чи це по іншому робиться в данному випадку.

2023-11-26 07:42 UTC, MZabolotnev approved these changes

2023-11-26 07:42 UTC, merged