7 arrays loops lesiaturuta
MastersAcademy/fe-course-basic-2023 pull request #334
Opened 2023-11-17 22:16 UTC by lesiaturuta

2023-11-20 22:32 UTC, oleg-nikulin-moc requested changes

2023-11-20 22:32 UTC, oleg-nikulin-moc commented on homeworks/lesia.turua_lesiaturuta/7-arrays-loops/arrays.js
> +        if (array[i] > maxNumber) {
Умова if (array[i]) може призвести до неправильних результатів, якщо елемент масиву дорівнює 0. Краще використовувати if (array[i] !== undefined && array[i] !== null).

2023-11-20 22:32 UTC, oleg-nikulin-moc commented on homeworks/lesia.turua_lesiaturuta/7-arrays-loops/arrays.js
> +    const startIndex = Number(initialValue);
Немає потреби використовувати Number(initialValue) для визначення startIndex. Просто починайте з індексу 0.

2023-11-21 15:54 UTC, lesiaturuta commented on homeworks/lesia.turua_lesiaturuta/7-arrays-loops/arrays.js
> +        if (array[i] > maxNumber) {
fixed line 42

2023-11-21 21:45 UTC, oleg-nikulin-moc approved these changes
Молодець, так тримати!

2023-11-21 21:45 UTC, merged