7-js_strings_dates_snischuk
MastersAcademy/fe-course-basic-2023 pull request #335
Opened 2023-11-18 07:25 UTC by snischuk

2023-11-20 22:43 UTC, oleg-nikulin-moc commented
я щось не зрозумів що ти тут робиш, 7 завдання по масивам

2023-11-21 21:49 UTC, oleg-nikulin-moc approved these changes

2023-11-21 21:54 UTC, oleg-nikulin-moc approved these changes

2023-11-24 20:46 UTC, oleg-nikulin-moc commented
я помітив одну проблему в тебе, навіть кілька якось странно той калькулятор працюєб він починає працювати  на зміну 1 інпута, та не завжди відмальовує картки. Глянь будь ласка

2023-11-24 20:47 UTC, oleg-nikulin-moc requested changes
я помітив одну проблему в тебе, навіть кілька якось странно той калькулятор працюєб він починає працювати на зміну 1 інпута, та не завжди відмальовує картки. Глянь будь ласка

2023-11-24 23:04 UTC, snischuk commented
> я помітив одну проблему в тебе, навіть кілька якось странно той калькулятор працюєб він починає працювати на зміну 1 інпута, та не завжди відмальовує картки. Глянь будь ласка

Таски "5-js-logic" та "7.5-js-strings_dates" виконані згідно умов у [цьому ТЗ](https://github.com/MastersAcademy/fe-course-basic-2023/issues/245):
> По бажанню: замість чисел в першому і останньому столбці можна виводити картки покемонів або ігор. Кількість карток має змінюватися дінамічно (подія onChange). Картки мають вишукуватися в стовбчик по 10 одна над іншою (margin-top: -50px або display: grid із необхідним разположенням). Максимальна кількість карток в першому стовбчику - 10, в останньому 100.

Встиг навішати "input" лише на перший операнд) 
Тобто при події "click" на кнопці "=" - рендер просто великих червоних чисел (за замовчуванням)
А при "input" - рендер карток з умовами (з лімітами 0 < перший-стовбчик <= 10 та 0 < останній-стовбчик <= 100)

2023-12-01 21:09 UTC, merged