7_HW_Task
MastersAcademy/fe-course-basic-2023 pull request #342
Opened 2023-11-18 18:58 UTC by NosatskyiK

2023-11-20 22:44 UTC, oleg-nikulin-moc requested changes
Щось тут багато закоментовано

2023-11-20 23:29 UTC, NosatskyiK commented
Розкоментував функції які використовував, так сталось бо працював з кожним кусочком окремо щоб не плутатись у виводі в консолі. Також виправив дрібні недоліки на які вказав лінтер (пробіли, крапки з комою, замінив звичайні функції на стрілочні)

2023-11-21 22:04 UTC, oleg-nikulin-moc requested changes

2023-11-21 22:04 UTC, oleg-nikulin-moc commented on homeworks/kostiantyn.nosatskyi_NosatskyiK/7-arrays-loops/arrays.js
> +    let minNumber = array[0];
Функції maxNumberOfArr, minNumberOfArr та sumNumbersOfArr не мають явної перевірки на undefined.

2023-11-21 22:04 UTC, oleg-nikulin-moc commented on homeworks/kostiantyn.nosatskyi_NosatskyiK/7-arrays-loops/arrays.js
> +    const stringLength = array.map((current) => current.length);
Вас просять написати функцію, яка повертає довжину елементу масиву, але ти використовуєш map для отримання довжин усіх елементів. Потрібно переписати цю функцію так, щоб вона повертала довжину конкретного елементу.

2023-11-23 18:53 UTC, NosatskyiK commented
1. Реалізував функцію так щоб умова числа більше та менше була передана з окремої функції (вивести суму не зміг таким чином).
2. Добавив рядок Number.isFinite(array[i])).
3. Добавив перевірку undefined в умову.
4. Цей коментар не дуже зрозумів, адже в issues було написано реалізувати кастомну функцію саме map, а наскільки я розумію цей метод перебирає всі елементи масиву і виводить новий масив враховуючи зміни, а для того щоб вивести довжину окремого елементу масиву цей метод не підходить, можу окремо це реалізувати, але тоді це буде суперечити завданню

2023-11-24 20:30 UTC, oleg-nikulin-moc commented
З приводу останього, то тобі і треба зробити функцію, яка буде імітувати перебір елементів map.  Тобто map в даному випадку не можна використовувати

2023-11-24 20:34 UTC, NosatskyiK commented
<img width="784" alt="image" src="https://github.com/MastersAcademy/fe-course-basic-2023/assets/78466086/0c941db7-9e73-4576-8317-cb7e3727490c">

тобто завдання з зірочкою це написати функцію яка буде працювати з масивом, але не використовувати reduce та map?

2023-11-25 19:34 UTC, NosatskyiK commented
Переписав функцію таким чином щоб вона приймала два аргументи (перший масив, а другий індекс елементу довжину якого потрібно дізнатись) і тепер виводить тільки довжину того елементу якого попросив юзер

2023-12-01 21:17 UTC, oleg-nikulin-moc approved these changes

2023-12-01 21:19 UTC, merged