7.5_HM_Task_NosatskyiK
MastersAcademy/fe-course-basic-2023 pull request #350
Opened 2023-11-19 17:01 UTC by NosatskyiK

2023-11-24 20:53 UTC, oleg-nikulin-moc commented
зроби завдання з зірочкою https://tppr.me/fdSFt гарненько з текстом і округленням, як на прикладі

2023-11-24 20:55 UTC, oleg-nikulin-moc commented on homeworks/kostiantyn.nosatskyi_NosatskyiK/7.5/js/homework.js
> +    document.querySelector('[data-timeBenchmark]').textContent = timeParcing;
Перенеси операції оновлення DOM (такі як nowDate і встановлення textContent для [data-timeBenchmark]) за межі функції calculate. Це дозволить функції calculate бути більш чистою, обробляти лише розрахунки, а оновлення DOM може бути здійснено в окремій функції або в точці виклику.

2023-11-24 20:58 UTC, oleg-nikulin-moc requested changes

2023-11-24 20:58 UTC, oleg-nikulin-moc commented on homeworks/kostiantyn.nosatskyi_NosatskyiK/7.5/js/homework.js
> +            result = firstValue / secondValue;
Додай обробку випадків, коли secondValue рівний 0, але операція є діленням ('/'). Зараз це може призвести до ділення на 0.

2023-11-24 20:58 UTC, oleg-nikulin-moc commented on homeworks/kostiantyn.nosatskyi_NosatskyiK/7.5/js/homework.js
> +        // performing mathematical operations
тут краще використовувати switch

2023-11-25 19:02 UTC, NosatskyiK commented
1. Додав текст до виводу дати та часу обробки, а також округлив запис часу виконання до десятих
2. Створив нову функцію за межами Calculate, а в самій функції Calculate тільки викликаю функцію executionTime.
3. Додав обробку події щоб в разі введення користувачем другого значення 0 при діленні, вивід просив його ввести коректне число.
4. Замінив if else на switch

2023-12-01 21:26 UTC, oleg-nikulin-moc approved these changes

2023-12-01 21:26 UTC, merged