7,5 task: strings, dates
MastersAcademy/fe-course-basic-2023 pull request #363
Opened 2023-11-21 20:10 UTC by NataMimoza

2023-11-24 21:09 UTC, oleg-nikulin-moc requested changes

2023-11-24 21:09 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/homework.js
> +            result = parseFloat(firstValue) + parseFloat(secondValue);
тут краще булоб використати константи для спрощення коду const firstNum = parseFloat(firstValue);

2023-11-24 21:09 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/homework.js
> +    const word = result > 1 || result < -1 ? 'games' : 'game';
не знаю чи ви проходили тернарні оператори, але якщо так то  тут було б гарно його застосувати

2023-11-25 16:38 UTC, NataMimoza commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/homework.js
> +            result = parseFloat(firstValue) + parseFloat(secondValue);
done

2023-11-25 16:38 UTC, NataMimoza commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/homework.js
> +    const word = result > 1 || result < -1 ? 'games' : 'game';
fixed

2023-12-01 21:28 UTC, oleg-nikulin-moc approved these changes

2023-12-01 21:28 UTC, merged