9-async_snischuk
MastersAcademy/fe-course-basic-2023 pull request #407
Opened 2023-12-04 14:54 UTC by snischuk

2023-12-18 05:08 UTC, snischuk commented
@oleg-nikulin-moc перевір, будь ласка, мульти-селект) мені він потрібний в 10ій гілці)

2023-12-18 20:15 UTC, oleg-nikulin-moc commented
> @oleg-nikulin-moc перевір, будь ласка, мульти-селект) мені він потрібний в 10ій гілці)
в мене селкт не працює, тобто класи додаються але немає фільтрації, також зроби що селект закривався коли ти клацаєш позв ним

2023-12-18 20:20 UTC, oleg-nikulin-moc requested changes
В мене філтрація в селекті так і не працює, класи додаються але фільтрації не відбувається, також. в дефолтному селктбокісі можна використовувати мцльтіселект, іноді краще дефолтні ui елементи використовувати ніж робити кастомні. Також зроби щоб кастомний селект закривався коли ти клікаєш ззовні.

2023-12-18 20:33 UTC, snischuk commented
> https://tppr.me/oCTUx

дефолний просто виглядає як в тебе на скріні (тому перейшов на кастомний)
типу не можна зробити як випадаючий список, чи я помиляюсь?))

2023-12-21 20:10 UTC, oleg-nikulin-moc commented
> > https://tppr.me/oCTUx
> 
> дефолний просто виглядає як в тебе на скріні (тому перейшов на кастомний) типу не можна зробити як випадаючий список, чи я помиляюсь?))

я може щось пропустив, але чим тобі не вгодив селект бокс? як для фільтрації він має норм підходити. істилі його можна кастомізувати під дизайн що надавався.

2023-12-22 10:52 UTC, snischuk commented
> > > https://tppr.me/oCTUx
> > 
> > 
> > дефолний просто виглядає як в тебе на скріні (тому перейшов на кастомний) типу не можна зробити як випадаючий список, чи я помиляюсь?))
> 
> я може щось пропустив, але чим тобі не вгодив селект бокс? як для фільтрації він має норм підходити. істилі його можна кастомізувати під дизайн що надавався.

не зміг нормально стилізувати <select> так як після добавлення йому атрибуту multiple - він виглядає як на скріні вище.. і щось зламався як його перестилізувати, тому зробив свій) крч то скоріш за все я щось пропустив))

2024-01-02 18:16 UTC, vladyslav-yermolin-moc commented
Hey, @snischuk, @oleg-nikulin-moc  the filtration functional of select is working, so I'm merging this pr into the main (cool UI, btw)

2024-01-02 18:17 UTC, vladyslav-yermolin-moc approved these changes

2024-01-02 18:17 UTC, merged