9-th task, async
MastersAcademy/fe-course-basic-2023 pull request #408
Opened 2023-12-04 20:22 UTC by NataMimoza

2023-12-06 20:53 UTC, oleg-nikulin-moc requested changes
було б дуже добре щоб ти підправила дизайн сайту https://tppr.me/jhsTw бо він не відповідає дизайнам що давали на уроках ментори

2023-12-06 20:53 UTC, oleg-nikulin-moc commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/games.js
> +    const containerElement = document.querySelector('.container[data-type=\'cards\']');
ти двічі викликаєш document.querySelector('.container[data-type=\'cards\']') це зайве

2023-12-11 15:53 UTC, NataMimoza commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/games.js
> +        filteredGames = games.filter((game) => new Date(game.release_date).getFullYear() > 2020);
додала

2023-12-11 15:53 UTC, NataMimoza commented on homeworks/Natalia.Alifirovets_NataMimoza/GamesProject/games.js
> +    const containerElement = document.querySelector('.container[data-type=\'cards\']');
видалила

2023-12-15 20:21 UTC, oleg-nikulin-moc approved these changes
Молодець

2023-12-15 20:22 UTC, merged