9 async vasyl biliak
MastersAcademy/fe-course-basic-2023 pull request #409
Opened 2023-12-05 16:10 UTC by VasylBiliak

2023-12-09 09:15 UTC, MZabolotnev requested changes
1) 
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/25617217/54d0a893-0a5b-42c4-9e27-2bf0bb766365)
Згідно завдання це мають бути radio, не чекбокси
2) 
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/25617217/dde431c4-a332-4d65-bd44-5eba34bea12b)
Має бути тільки три варіанта сортування всі ( при першому завантаженні сторінки, або коли ніякий з radio не чекнутий ), спочатку нові, спочатку старі. Використовуй для цього sort-by=release-date, та роби наприклад реверс массиву. Ти ж передаєш дату в запиті, що не дуже зрозуміло навіщо 
3) 
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/25617217/29caa12a-acdb-4434-be8a-f5b7156bc0de)
Що роблять оці елементи? Там має бути селект по категоріям

2023-12-16 16:30 UTC, MZabolotnev commented
Є конфлікти, які треба зарезолвить

2023-12-18 09:29 UTC, VasylBiliak commented
Я виправив
сб, 16 груд. 2023 р. о 18:30 Miron Zabolotniev ***@***.***>
пише:

> Є конфлікти, які треба зарезолвить
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MastersAcademy/fe-course-basic-2023/pull/409#issuecomment-1858861322>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BDGRTUGJMWJMGWPBWC4N5CLYJXEDVAVCNFSM6AAAAABAH6GPSGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJYHA3DCMZSGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-12-19 16:46 UTC, MZabolotnev approved these changes

2023-12-19 16:46 UTC, merged