10-final_snischuk
MastersAcademy/fe-course-basic-2023 pull request #425
Opened 2023-12-14 05:18 UTC by snischuk

2023-12-14 17:02 UTC, vladyslav-yermolin-moc commented
Hey, @snischuk, please add a link to your deployed project
> Зробіть пуллреквест із посиланням на ваш задеплоїний проєкт

2023-12-14 17:47 UTC, vladyslav-yermolin-moc requested changes

2023-12-14 17:47 UTC, vladyslav-yermolin-moc commented on homeworks/max.snischuk_snischuk/PokemonProject/styles/base.css
> +
please add a `min-width`
> Зробіть резінову верстку:
> мінімальна ширина контенту - 400px (меньше - зʼявляється скрол)

2023-12-14 17:47 UTC, vladyslav-yermolin-moc commented on homeworks/max.snischuk_snischuk/PokemonProject/index.html
> +                <img class="about__image" src="./images/about.jpeg" alt="pokemon">
As a recommendation: the language of your site is English, but you have the Ukrainian error messages. Looks inconsistent.
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/98031768/4cc78eaf-c649-442b-adb0-89e293b76e0b)

2023-12-14 17:47 UTC, vladyslav-yermolin-moc commented on homeworks/max.snischuk_snischuk/PokemonProject/index.html
> +                <img class="about__image" src="./images/about.jpeg" alt="pokemon">
The height of the input is different for normal and focus states - it leads to `content-jumping`
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/98031768/f21c7000-5fd8-4647-93be-5ce5d26d1529)
![Screenshot at Dec 14 19-19-45](https://github.com/MastersAcademy/fe-course-basic-2023/assets/98031768/5c4cd906-c2a7-467f-945d-24e31dc4ad9b)

2023-12-14 17:47 UTC, vladyslav-yermolin-moc commented on homeworks/max.snischuk_snischuk/PokemonProject/pokemons.html
> +                        <input class="filters__input" id="favorites" type="radio" name="radio-options"
Your logic of filtering broken a bit:
1. Check Small checkbox
2. Type s in the search
3. I see big pokemons which go to hidden when the input lost focus (any click)

![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/98031768/d3362500-fafc-4bb7-98c4-a0326eeed1d6)

2023-12-14 17:47 UTC, vladyslav-yermolin-moc commented on homeworks/max.snischuk_snischuk/PokemonProject/pokemons.html
> +                        <input class="filters__input" id="favorites" type="radio" name="radio-options"
It is good, that you used `featured` prop of the Pokemons for the filtering by radio, but not a user can't understand, what is going on, when they hit `Favorite` radio.
Would be good to add some visual representation to the card (e.g. heart icon or another badge)
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/98031768/c72e1474-d908-4050-8bb6-90077f22e149)

2023-12-14 17:47 UTC, vladyslav-yermolin-moc commented on homeworks/max.snischuk_snischuk/PokemonProject/calculator.html
> +        <footer class="footer">
Same content jumps I can see on this page, when both inputs are filled and I hit `=` button

2023-12-15 19:40 UTC, snischuk commented
@vladyslav-yermolin-moc Very useful comments!) Thanks for review!)
P.S sorry for pokemons-filters, i forgot that main branch is without "9-async_snischuk" branch)

2023-12-26 12:33 UTC, vladyslav-yermolin-moc commented
Hey, @snischuk, please deploy you project and add a link to it here. Also please move your project files to `docs` folder and add a link to `docs/index.html` as described in https://github.com/MastersAcademy/fe-course-basic-2023/issues/423

2024-01-02 18:19 UTC, vladyslav-yermolin-moc commented
Hey, @snischuk ,I've merged your task 9 pr, so, you have some time to finish your project and deploy it to our[ "Hall of Fame" ](https://mastersacademy.github.io/fe-course-basic-2023/)

2024-01-03 08:45 UTC, closed without merging