10-final_SerhiiNSN
MastersAcademy/fe-course-basic-2023 pull request #428
Opened 2023-12-16 17:51 UTC by SerhiiNSN

Link to deployed project - https://serhiinsn.github.io/fe-course-basic-2023/

2023-12-17 18:06 UTC, vladyslav-yermolin-moc requested changes
Good work 👍

2023-12-17 18:06 UTC, vladyslav-yermolin-moc commented on docs/SerhiiNSN/scripts/burger.js
> +    burger.classList.toggle('active');
Proly you can find more suitable names for these classes, like `opened`, `no-scroll` e.g.

2023-12-17 18:06 UTC, vladyslav-yermolin-moc commented on docs/SerhiiNSN/scripts/games.js
> +async function createCardElement(game) {
Why do you make this function `async`? There is no async operation in it.

2023-12-17 18:06 UTC, vladyslav-yermolin-moc commented on docs/SerhiiNSN/scripts/games.js
> +    await Promise.all(games.map(async (game) => {
... then you can skip this `await Promise.all` and make the current function synchronous too.

2023-12-19 19:56 UTC, vladyslav-yermolin-moc commented on docs/SerhiiNSN/games.html
> +                            <div class="card__about">
This `line-height: 150%` makes the text row taller 
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/98031768/2fcef1e9-4d75-4e1f-bc46-9ca6ddf84a36)
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/98031768/6c864887-c1ec-4fae-9905-982232806e4c)

2023-12-19 19:57 UTC, vladyslav-yermolin-moc commented on docs/SerhiiNSN/games.html
> +                            <div class="card__about">
And add please decent class name https://github.com/MastersAcademy/fe-course-basic-2023/issues/426#issue-2042776096
> Задавайте стилі лише на класи (не на елементи)

2023-12-19 19:58 UTC, vladyslav-yermolin-moc submitted a review, later dismissed
Good, I can approve this pr, please fix those minor comments in the nearest future

2023-12-20 09:42 UTC, vladyslav-yermolin-moc approved these changes

2023-12-25 08:39 UTC, MZabolotnev approved these changes

2023-12-25 15:45 UTC, merged