10 final demasha0908
MastersAcademy/fe-course-basic-2023 pull request #430
Opened 2023-12-16 22:36 UTC by demasha0908

Link to deployed project - https://demasha0908.github.io/fe-course-basic-2023/

2023-12-21 20:30 UTC, oleg-nikulin-moc commented on docs/demasha0908/css/style.css
> +  margin-top: 60px;
Намагайся не використовувати margin-top бо в майбутньому може зустрічати таке явище як  margin collapsing ,можеш почитати що це таке https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_box_model/Mastering_margin_collapsing.

2023-12-21 20:30 UTC, oleg-nikulin-moc requested changes
Вибач, що довго не перевіряв, на мобайлі тут є проблема https://tppr.me/6hJrcg, такст злипся, потрібно додати line-height. також за великі падінгі ідля карток на мобайлі можна зробити ширину на 100% до певної ширини єкрану, щоб було гарно і якісь падінги для контейнера. Також сама картка не симетрично виглядає. На Ipad також трохи поїхало, походу щось кудись не влазить. https://tppr.me/3ZVJR2

2023-12-21 20:36 UTC, oleg-nikulin-moc commented
[Db](https://github.com/MastersAcademy/fe-course-basic-2023/issues/426) не забудь пройтися по чеклісту

2024-01-05 17:17 UTC, MZabolotnev approved these changes

2024-01-08 22:13 UTC, vladyslav-yermolin-moc commented
I've resolved the conflict in the index.html and gonna merge this pr

2024-01-08 22:13 UTC, merged