10-Final homework
MastersAcademy/fe-course-basic-2023 pull request #434
Opened 2023-12-19 23:53 UTC by Rooosss

Link to deployed project - https://rooosss.github.io/fe-course-basic-2023/

2023-12-20 21:23 UTC, vladyslav-yermolin-moc requested changes
Good work! Thanks

2023-12-20 21:23 UTC, vladyslav-yermolin-moc commented on docs/rooosss/index.html
> +            <header class="header">
Are these white gaps ok for you?
I suggest moving the background-color to the `.header` and `.footer` correspondently.
![Screenshot at Dec 20 22-58-46](https://github.com/MastersAcademy/fe-course-basic-2023/assets/98031768/473d1d2c-244f-4d96-8d1d-fe81087d1ba0)

2023-12-20 21:23 UTC, vladyslav-yermolin-moc commented on docs/rooosss/scripts/pokemons.js
> +        if (isBigSizeFilterChecked && card.height >= 100) {
I suggest using some other values, lest say 20'' and 50``. That would add a visual representation of clicking `big` checkbox.
And you can add it as a description to checkboxes texts: `Big(>50'')`

2023-12-20 21:23 UTC, vladyslav-yermolin-moc commented on docs/rooosss/scripts/pokemons.js
> +        if (isBigSizeFilterChecked && card.height >= 100) {
you can use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter for the filtering propose
Also 
> При обраних чекбоксах Big та Small  - покемони нижче 50' та вище 100'

Now when both checkboxes are checked a user can see only small pokemons

2023-12-20 21:23 UTC, vladyslav-yermolin-moc commented on docs/rooosss/scripts/pokemons.js
> +        if (isBigSizeFilterChecked && card.height >= 100) {
And you can declare the filters values (20 and 50) as constants on the top of the script with some decent name. [Magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)) - is an antipattern

2023-12-20 21:23 UTC, vladyslav-yermolin-moc commented on docs/rooosss/style/footer.css
> +footer__image-container a {
this selector is broken and useless. The `a` elements have `cursor: pointer;` by default
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/98031768/ffb38f69-b069-4f0b-b056-913b7530c62a)

2023-12-24 11:52 UTC, vladyslav-yermolin-moc approved these changes

2023-12-24 11:52 UTC, vladyslav-yermolin-moc commented on docs/rooosss/pokemons.html
> +                    <section class="filters">
Same gaps now you have for filters. Proly you can lift up filters block out of main 
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/98031768/1ba3592b-0774-462f-baa7-34cfe03e41b3)

2023-12-25 15:15 UTC, vladyslav-yermolin-moc approved these changes

2023-12-29 16:45 UTC, vadym-zinchenko-moc commented
![Screenshot 2023-12-29 at 18 42 51](https://github.com/MastersAcademy/fe-course-basic-2023/assets/115080771/cc911257-c3e1-45f3-9171-93b45ba148b8)

I don't see any responsive layout at all

2023-12-29 16:49 UTC, vadym-zinchenko-moc commented
Thanks! Really fine project!

2023-12-29 16:51 UTC, vadym-zinchenko-moc commented
need to resolve conflict and I can merge it!

2023-12-30 21:43 UTC, vadym-zinchenko-moc approved these changes

2023-12-30 21:44 UTC, merged