feat: add footer and adaptive layout
MastersAcademy/fe-course-basic-2023 pull request #441
Opened 2023-12-23 12:31 UTC by vBrusentsov

end tasks with star

2023-12-25 09:11 UTC, MZabolotnev requested changes
Все круто, гарна робота! Є пару зауважень:
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/25617217/d8fb788b-dd0d-40b6-b9bf-8ab47a4c152e)
1) Вирівнять фільтри по одній лініі
2) Тест в титулкі Games без відступу
3) Краще зробити картки в одну колонку, і там теж є трохи біда з текстом
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/25617217/1c5bc474-be77-47fb-a239-f7c481b313bc)
1) Відступи різні
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/25617217/259da838-d377-46f4-8898-da36bc6554b5)
Цей скрін відрізняється від інших
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/25617217/c02a7424-c3bc-438b-8260-c268ce77a6fa)
Обрізаний плейсхолдер паролю

2023-12-28 15:26 UTC, MZabolotnev submitted a review, later dismissed

2024-01-06 19:29 UTC, vladyslav-yermolin-moc commented on docs/index.html
> +                    Vladyslav Brusentsov - <a href="./vBrusentsov/about.html">Games Project</a>
Hey, @vBrusentsov, why do you delete and change so many files of other students or even lecturers?
You should only add your changes, not delete any work of your colleagues.

Please revert these changes.

And here you should add the links to your project without deleting other student's link.
```suggestion
 <li>
                    Serhii Noskov - <a href="./SerhiiNSN/index.html">Final Project</a>
</li>
<li>
                    Vladyslav Brusentsov - <a href="./vBrusentsov/about.html">Games Project</a>
</li>
```

2024-01-07 18:33 UTC, vladyslav-yermolin-moc commented
Hey, @vBrusentsov, you should remove **changes** of the files, not **delete** files. I've wrote you simple way in tg
- make a new branch from the fresh main
- add you files to `docs` folder
- create pr

2024-01-08 21:41 UTC, vladyslav-yermolin-moc commented
OK, I'm closing this pr and waiting for the correct one

2024-01-08 21:41 UTC, closed without merging