10-final_adaptiv, deploy, layout
MastersAcademy/fe-course-basic-2023 pull request #445
Opened 2023-12-25 11:44 UTC by NosatskyiK

Посилання на проект
https://nosatskyik.github.io/Pokemon-Project/kostiantyn.nosatskyi/PokemonProject/index.html

2023-12-26 20:28 UTC, oleg-nikulin-moc requested changes
на мобайлі краще такі блоки розтігувати на всю ширину,  можна з падінгом невеликим, або до прикладу width :90%; margin-left: auto; margin-right: auto;  тоді мобайл вью буде краще виглядати

2023-12-26 20:28 UTC, oleg-nikulin-moc commented on docs/kostiantyn.nosatskyi/PokemonProject/login.css
> +  .btn__submit {
намагайся не викорстовувати with з px це харкодить ширину і можуть вилазити певні баги при респонсі, в кнопках краще падінги або max-width, min width, якщо width то у %

2023-12-26 20:28 UTC, oleg-nikulin-moc commented on docs/kostiantyn.nosatskyi/PokemonProject/style.css
> +  width: 190px;
те саме з імеджами, з ними краще задавати width: 100%; max-width: 190px: height: auto; і картинка ніколи не буде ламатися чи спотворюватися

2023-12-26 20:28 UTC, oleg-nikulin-moc commented on docs/kostiantyn.nosatskyi/PokemonProject/style.css
> +  width: 532px;
те саме, використовуй резинову верстку

2023-12-26 20:28 UTC, oleg-nikulin-moc commented on docs/kostiantyn.nosatskyi/PokemonProject/style.css
> +    max-width: 100%;
краще просто width: 100%

2023-12-26 20:28 UTC, oleg-nikulin-moc commented on docs/kostiantyn.nosatskyi/PokemonProject/successful.css
> +    max-width: 100%;
max-width: зайве

2023-12-26 20:28 UTC, oleg-nikulin-moc commented on docs/kostiantyn.nosatskyi/PokemonProject/successful.css
> +    width: 320px;
писав про падінги

2024-01-01 20:19 UTC, NosatskyiK commented
Замінив для фото та інпутів width з "px" на "%". Розтягнув інпути в логіні та калькуляторі для мобайл версії на 80% (по 10 залишилось на відступи). Зробив гнучким поле пошуку, щоб при зменшенні екрану зменшувався і search bar

2024-01-05 17:14 UTC, MZabolotnev approved these changes
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/25617217/4404318f-e31b-4dc7-b50c-4b477cd7fcff)
Було б непогано вирівнять вертикально ці елементи по одній лініі зліва. Але це не критичний фікс, апрувлю

2024-01-06 20:52 UTC, NosatskyiK commented
@MZabolotnev Привіт. Підскажи, будь ласка, був конфлікт злиття і я його виправив,  а потім зʼявилось ось це повідомлення, 
<img width="901" alt="image" src="https://github.com/MastersAcademy/fe-course-basic-2023/assets/78466086/53649e61-6784-43d4-b886-9406b29d5c4e">
не потрібно було краще виправляти конфлікти чи це нормально?

2024-01-08 22:21 UTC, vladyslav-yermolin-moc approved these changes
I'm gonna merge this pr, thanx for your work, @NosatskyiK

2024-01-08 22:22 UTC, merged