10-final_Bogdandrummer
MastersAcademy/fe-course-basic-2023 pull request #448
Opened 2023-12-26 12:15 UTC by Bogdandrummer

Link to deployed project 
https://bogdandrummer.github.io/fe-course-basic-2023/

2024-01-05 17:34 UTC, MZabolotnev requested changes
Привіт! Дякую за круту роботу) 
Є пару побажань: 
1) Тут не вистачає паддінгу справа
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/25617217/de27c628-6f98-4a33-963e-30a3ee1042b8)
2) Елементи меню маленькі і не дуже зручні з мобільних девайсів. Спробуй розташувати іх по всьому вільному місцю і трохи збільшити.
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/25617217/fb7c9d3c-2b0b-4c65-814d-208279f04aab)

2024-01-07 12:12 UTC, vadym-zinchenko-moc requested changes

2024-01-07 12:12 UTC, vadym-zinchenko-moc commented on homeworks/bogdan.yatsentiuk_Bogdandrummer/GamesProject/js/games.js
> +buttonTop.addEventListener('click', changeFilter);
адаптив робимо за допомогою css

2024-01-07 12:12 UTC, vadym-zinchenko-moc commented on homeworks/bogdan.yatsentiuk_Bogdandrummer/GamesProject/html/login.html
> -                    <!--Menu list-->
коментарі мають бути видалені по всьому проекту

2024-01-07 12:12 UTC, vadym-zinchenko-moc commented on docs/Bogdandrummer/html/games.html
> +                        <input type="search" class="search__input" id="search__input" name="search" placeholder="Search">
інпут не працює тому має бути задізейбленим

2024-01-07 12:12 UTC, vadym-zinchenko-moc commented on docs/Bogdandrummer/js/games.js
> +        }
не потрібна перевірка і вручну робити помилку (якщо щось піде не так в нас піде в catch )

2024-01-07 12:12 UTC, vadym-zinchenko-moc commented on docs/Bogdandrummer/js/games.js
> +window.addEventListener('resize', mainMenuEvent);
немає функції ініт як прописано в задачі

2024-01-11 12:28 UTC, vladyslav-yermolin-moc approved these changes
Hey, @Bogdandrummer, thanks for your work during the course

2024-01-11 12:28 UTC, merged