added homework 10-final
MastersAcademy/fe-course-basic-2023 pull request #451
Opened 2023-12-27 19:46 UTC by DavidTereshchenko

2023-12-27 22:00 UTC, anna-vrana-moc commented
Hi @DavidTereshchenko please provide the link to you project in the description here

2023-12-28 12:51 UTC, DavidTereshchenko commented
> Hi @DavidTereshchenko please provide the link to you project in the description here

https://davidtereshchenko.github.io/Game-Project/

2024-01-01 03:59 UTC, anna-vrana-moc commented
Happy Hew Year @DavidTereshchenko!
I'm starting the review
1) You can improve responsive like
<img width="657" alt="Screenshot 2024-01-01 at 05 56 53" src="https://github.com/MastersAcademy/fe-course-basic-2023/assets/118203044/defb4890-f658-41a6-a376-7177d3fd8827">

2024-01-01 04:40 UTC, anna-vrana-moc requested changes

2024-01-01 04:40 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/calculator.html
> +                    <div class="calculator__container">
It is an unnecessary wrap. Please remove it

2024-01-01 04:40 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/calculator.html
> +                            </div>
You can remove  `<div class="number-1">` and simplify your code:
```
<label for="firstNumber">First number
       <input id="firstNumber" data-number-one="one" class="number__block one" name="number1" required>
</label>
```

2024-01-01 04:40 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/calculator.html
> +                            <div class="operator__block">
It is an unnecessary wrap. Please remove it

2024-01-01 04:40 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/calculator.html
> +                            </div>
The same story:
You can remove `<div class="number-2">` and simplify your code:

```
<label for="secondNumber">First number
      <input id="secondNumber" data-number-two ="two" class="number__block one" name="number2" required>
</label>
```

2024-01-01 04:40 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/calculator.html
> +                            <div class="return">
It is an unnecessary wrap. Please remove it

2024-01-01 04:40 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/calculator.html
> +                            <div class="visual-counting">
The div above is an unnecessary wrap. Please remove it and add `class="count-block" data-count-block="count-block"` to `visual-counting` block

2024-01-01 04:40 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/css/calculator.css
> +  display: flex;
This property is useful for aligning blocks. Avoid using it for strings

2024-01-01 04:40 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/css/calculator.css
> +.visual-counting span {
You'll get the same result without the span. Simplify the code and avoid specifying unnecessary styles

2024-01-01 04:40 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/css/calculator.css
> +}
You can remove 
  ```
display: flex;
  flex-direction: row;
  align-items: center;
```
 and keep the same visual. So let's do it)

2024-01-01 04:40 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/css/calculator.css
> +}
You need to specify only `font-size: 14px; ` here, so you can remove unnecessary code

2024-01-01 04:40 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/css/calculator.css
> +  flex-direction: row;
by default `display: flex` has `flex-direction: row; ` so you don't need to write it unless you switch between column and row layouts

2024-01-01 04:40 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/css/calculator.css
> +  flex-direction: row;
please remove ` flex-direction: row;`

2024-01-01 04:40 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/css/calculator.css
> +}
I believe, you can remove all styles:
```
.oper {
  display: flex;
  align-items: center;
  justify-content: center;
}
```

2024-01-01 04:40 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/calculator.html
> +                                <span class="count-games__visual" data-count-game-visual="count-game"></span>
You can remove classes from each `span` since you don't have any specific styles for them

2024-01-01 04:53 UTC, anna-vrana-moc commented
I like your mobile filter icon
<img width="658" alt="Screenshot 2024-01-01 at 06 52 57" src="https://github.com/MastersAcademy/fe-course-basic-2023/assets/118203044/83f3ebe1-87f8-4ce2-8e88-b0545fcf6bb3">

2024-01-01 04:57 UTC, anna-vrana-moc commented
2) Please fix the default outline on the select:
<img width="1227" alt="Screenshot 2024-01-01 at 06 55 46" src="https://github.com/MastersAcademy/fe-course-basic-2023/assets/118203044/e789d658-bec4-4d63-84b9-ec872df77d64">

2024-01-01 05:23 UTC, anna-vrana-moc commented
3) Please add common padding of 15px here also
<img width="626" alt="Screenshot 2024-01-01 at 07 21 59" src="https://github.com/MastersAcademy/fe-course-basic-2023/assets/118203044/bd5eb671-eb96-441f-b927-e96924ad411a">

2024-01-01 05:35 UTC, anna-vrana-moc requested changes

2024-01-01 05:35 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/script/cards.js
It is better to use similar names for all files on the page. So, rename this file to `'game.js'` like `'game.html'`, `'game.css'`

2024-01-01 05:35 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/script/cards.js
> +sortFilter();
You can use `'function  init'` to call all functions

2024-01-01 05:35 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/script/cards.js
> +    showLoader();
You can create the `function search` and just use it here

2024-01-01 05:35 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/css/successful.css
> +}
You can remove this styles

2024-01-01 05:35 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/successful.html
> +                        <div class="success">
You can remove this wrap and just use text-align: center for `success-block`

2024-01-01 05:35 UTC, anna-vrana-moc commented on docs/DavidTereshchenko/successful.html
> +                        <form action="game.html" class="success__form">
You can add the class `success__back-home` and remove the block below

2024-01-08 05:13 UTC, anna-vrana-moc submitted a review, later dismissed

2024-01-08 05:16 UTC, anna-vrana-moc commented
@DavidTereshchenko thank you for the all fixes. You are ready for final review! @MZabolotnev if you have a chance, please take a look and add your review :)

2024-01-11 12:34 UTC, vladyslav-yermolin-moc requested changes

2024-01-11 12:34 UTC, vladyslav-yermolin-moc commented on docs/SerhiiNSN/calculator.html
Hey, @DavidTereshchenko, I could merge your pr, but you deleted the work of your colleague. Please move these files in the folder `SerhiiNSN` back and I' merge your pr
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/98031768/0ca847c4-be6c-4cd2-9cef-4b327fc01a81)

2024-01-12 09:55 UTC, anna-vrana-moc approved these changes

2024-01-12 09:55 UTC, anna-vrana-moc commented on docs/SerhiiNSN/calculator.html
it is fixed now

2024-01-12 10:09 UTC, vladyslav-yermolin-moc approved these changes

2024-01-12 10:09 UTC, merged