card template created
MastersAcademy/fe-course-basic-2023 pull request #464
Opened 2024-02-28 20:09 UTC by NosatskyiK

2024-03-07 07:51 UTC, IgorFromUA commented
Hello. You can customize the container to align the content.
![1](https://github.com/MastersAcademy/fe-course-basic-2023/assets/109870514/58bd707b-e68a-4330-a8b7-b62ef8c6d3ce)
![2](https://github.com/MastersAcademy/fe-course-basic-2023/assets/109870514/c50cd666-c202-419a-9fe1-95c47ab0772d)

2024-03-10 18:00 UTC, NosatskyiK commented
> Hello. You can customize the container to align the content. ![1](https://private-user-images.githubusercontent.com/109870514/310790946-58bd707b-e68a-4330-a8b7-b62ef8c6d3ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwOTM5MjYsIm5iZiI6MTcxMDA5MzYyNiwicGF0aCI6Ii8xMDk4NzA1MTQvMzEwNzkwOTQ2LTU4YmQ3MDdiLWU2OGEtNDMzMC1hOGI3LWI2MmVmOGM2ZDNjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQxODAwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWUwYzkxM2YzNGNkYjU4MDUyODAyMjM4YTUxNTQ1NzEyOGJmYzIyOGQwYmYxMWRlYjNlZjc1ZTBjY2UyNjA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JM2pr5F8V-UoTU1lcERtTxSVMUyKm7cd4D_YWt_sMJk) ![2](https://private-user-images.githubusercontent.com/109870514/310791002-c50cd666-c202-419a-9fe1-95c47ab0772d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwOTM5MjYsIm5iZiI6MTcxMDA5MzYyNiwicGF0aCI6Ii8xMDk4NzA1MTQvMzEwNzkxMDAyLWM1MGNkNjY2LWMyMDItNDE5YS05ZmUxLTk1YzQ3YWIwNzcyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQxODAwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGRjYTc5OGZhYjMxZDgwZWVjZTQxM2JiM2E2OGQwYzM4NTFlM2JiODU1MDA1MDU1NGZlYzAwZDljZjJkY2VkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mszY6H-nutKFsII7mC5Vp6JSHlNU01-iLXZZhJs1DVc)

Hello, Bohdan worked with the text, so I think it would be correct to write to him about the text on the page

2024-03-12 19:48 UTC, Bogdandrummer approved these changes

2024-03-15 16:17 UTC, NosatskyiK commented on docs/index.html
> +                        <div class="card__btn">
removed unused tag classes

2024-03-17 11:00 UTC, vladyslav-yermolin-moc commented
Hey, guys, I've added some minor styles corrections, and going to make a code-review

2024-03-17 11:01 UTC, vladyslav-yermolin-moc commented
The icons in the footer are blocked by CORS 
![image](https://github.com/MastersAcademy/fe-course-basic-2023/assets/98031768/93ed84d4-630f-48aa-89d1-ade31970eede)

2024-03-17 11:41 UTC, vladyslav-yermolin-moc commented
Ok, the Github pages don't like the underscores in the file name (probably).
So I've changed the files structure and corrected the pathes
Here is deployed version (on my Github pages) https://vladyslav-yermolin-moc.github.io/fe-course-basic-2023/

2024-03-17 11:47 UTC, vladyslav-yermolin-moc requested changes

2024-03-17 11:47 UTC, vladyslav-yermolin-moc commented on docs/src/styles/null.css
What a name!!!)))
Please use more common: reset or normalize.css

2024-03-17 11:47 UTC, vladyslav-yermolin-moc commented on docs/src/styles/style.css
> +  font-family: Roboto sans-serif;
Something wrong with font connection - please don't forget to add safe font and tune up connection of Roboto properly

2024-03-17 11:47 UTC, vladyslav-yermolin-moc commented on docs/src/styles/styles.css
Probably, the `card.css` would be more suitable name

2024-03-17 11:47 UTC, vladyslav-yermolin-moc commented on docs/src/styles/style.css
Please add some suitable name for this file

2024-03-17 12:01 UTC, vladyslav-yermolin-moc commented
I'm going to merge this pr, but fixes of my comments here are on you, @NosatskyiK

2024-03-17 12:01 UTC, merged