11 hall of fame page layout bogdandrummer
MastersAcademy/fe-course-basic-2023 pull request #476
Opened 2024-03-21 16:25 UTC by Bogdandrummer

2024-03-22 07:26 UTC, AndriiMorozov88 commented
Картки вистроюються в одну колонку при ширині екрана 640px, стрілка вгору з'являється при ширині екрана 599 рх... якось нелогічно.

const arrowAppearance = () => {
    if (window.innerWidth < 602 || window.innerWidth > 602) {
        checkScroll();
    }
};
не зовсім розумію умову в функції... по суті тут виключене тільки число 602 при якому запускається функція

2024-03-22 08:26 UTC, vladyslav-yermolin-moc requested changes

2024-03-22 08:26 UTC, vladyslav-yermolin-moc commented on docs/index.html
> +            content="student projects created on the course «Front-End for Beginners 2023» by Master of Academy">
```suggestion
            content="List of projects created by students of the Front-End for Beginners 2023 course at Masters Academy.">
```

2024-03-22 08:26 UTC, vladyslav-yermolin-moc commented on docs/src/styles/style.css
> +@media (max-width: 997px) {
Please add a CSS variable (e.g. `--tabletWidth`)

2024-03-22 09:57 UTC, IgorFromUA reviewed
Hi. It seems to me that it is necessary to remove the "font-family" from all classes except  class ".body".

2024-03-26 09:01 UTC, IgorFromUA requested changes

2024-03-26 09:18 UTC, Bogdandrummer commented on docs/src/styles/style.css
> +body {
But page styles file in style.css.
card.css - styles of cards

2024-03-29 10:37 UTC, vladyslav-yermolin-moc commented on docs/src/styles/style.css
> +body {
So we should remove the global styles from `cards.css`

2024-03-29 10:37 UTC, vladyslav-yermolin-moc commented on docs/src/styles/style.css
>  @import url("https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500;1,600;1,700;1,800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;1,100;1,300;1
Good catch, will fix in the next upadte.

2024-03-29 10:38 UTC, vladyslav-yermolin-moc commented on docs/src/styles/style.css
> +@media (max-width: 997px) {
It is not supported, as I understood

2024-03-29 10:39 UTC, vladyslav-yermolin-moc approved these changes
Hey, @Bogdandrummer, I've resolved the conflict in `index.html` for you

2024-03-29 10:39 UTC, merged