homework_1
MastersAcademy/fe-course-basic-2023 pull request #94
Opened 2023-10-19 06:54 UTC by vitaliykonak

2023-10-20 16:41 UTC, MZabolotnev requested changes

2023-10-20 16:41 UTC, MZabolotnev commented on homeworks/vitaliy.konak_vitaliykonak/GamesProject/index.html
> +
`main`  block should be inside the body block. The body block should not be empty

2023-10-25 06:26 UTC, MZabolotnev commented on homeworks/vitaliy.konak_vitaliykonak/GamesProject/index.html
> +
@vitaliykonak please fix this

2023-10-25 18:56 UTC, vladyslav-yermolin-moc commented
I'm closing this pr, because of deadline is gone

2023-10-25 18:56 UTC, closed without merging